import { ArrowRight, ChevronRight, Download, Plus, Search, Trash2, Upload } from "lucide-react";
import { Poster } from "../components/Poster";
import { IconButton } from "./IconButton";
import { heading } from "./helpers";
import { MAX_PROFILE_BYTES } from "../lib/profile";
import type { SourceViewProps } from "./types";

export function SourceView({ kind, t, label, source, setSource, setNotice, search, setSearch, colCount, changeCols, collections, openCollection, customItem, setCustomItem, addCustomItem, customText, setCustomText, importCollection, saveCollectionCloud, cloudCollections, loadCloudCollections, deleteCloudCollection, doubanLimit, setDoubanLimit, busy, loadDouban }: SourceViewProps) {
  return <>
    {heading(`${label(kind)} / ${t("清单", "LIST")}`, t("先选一份清单", "Choose a list"), t("从熟悉的作品开始，或者把自己的收藏带进来。", "Start with a familiar list, or bring your own collection."))}
    <div className="segmented" role="tablist" aria-label={t("清单来源", "List source")}>{(["builtin", "custom", ...(kind === "film" || kind === "book" || kind === "music" ? ["douban"] : [])] as Array<"builtin" | "custom" | "douban">).map((item) => <button key={item} role="tab" aria-selected={source === item} className={source === item ? "active" : ""} onClick={() => { setSource(item); setNotice(""); }}>{item === "builtin" ? t("精选清单", "Curated") : item === "custom" ? t("我的清单", "My list") : t("豆瓣精选", "Douban")}</button>)}</div>
    {source === "builtin" && <><div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 12 }}><label className="search-field" style={{ flex: 1, marginBottom: 0 }}><Search size={17} /><input aria-label={t("搜索榜单", "Search collections")} placeholder={t("搜索榜单或作品", "Search collections or works")} value={search} onChange={(event) => setSearch(event.target.value)} /></label><div style={{ display: "flex", gap: 4 }}>{[2,3,4].map(n => <button key={n} onClick={() => changeCols(n)} style={{ width: 32, height: 32, borderRadius: 8, border: colCount === n ? "1px solid var(--accent)" : "1px solid var(--line)", background: colCount === n ? "rgba(216,248,106,.1)" : "transparent", color: colCount === n ? "var(--accent)" : "var(--muted)", fontSize: 12, fontWeight: 600, cursor: "pointer" }}>{n}</button>)}</div></div><div className="collection-list" style={{ gridTemplateColumns: `repeat(${colCount}, minmax(0, 1fr))` }}>{collections.map((item, index) => <button key={item.id} className="collection-row" onClick={() => openCollection(item)}><span className="row-number">{String(index + 1).padStart(2, "0")}</span>{item.works[0] && <Poster work={item.works[0]} kind={item.kind} />}<div><h3>{item.title}</h3><small>{item.works.length} {t("件作品", "works")}</small></div><ChevronRight size={18} /></button>)}{!collections.length && <p className="empty-state">{t("没有匹配的榜单。", "No matching collections.")}</p>}</div></>}
    {source === "custom" && <section className="import-form"><label htmlFor="custom-item">{t("快速添加一件作品", "Add one work")}</label><div className="inline-input"><input id="custom-item" value={customItem} onChange={(event) => setCustomItem(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") addCustomItem(); }} placeholder={t("输入标题后回车", "Type a title and press Enter")} /><button className="button secondary" onClick={addCustomItem}><Plus size={16} />{t("加入清单", "Add")}</button></div><label htmlFor="custom-list">{t("批量清单", "Batch list")}</label><textarea id="custom-list" value={customText} onChange={(event) => setCustomText(event.target.value)} placeholder={t("每行一件，也支持逗号、TXT 或 JSON", "One work per line, commas, TXT, or JSON")} /><div className="action-row"><label className="button secondary file-button"><Upload size={16} />{t("打开 TXT / JSON", "Open TXT / JSON")}<input type="file" aria-label={t("导入作品清单", "Import collection")} accept=".txt,.json,text/plain,application/json" onChange={async (event) => { const file = event.target.files?.[0]; if (file && file.size <= MAX_PROFILE_BYTES) setCustomText(await file.text()); else if (file) setNotice(t("文件超过 512 KB。", "File exceeds 512 KB.")); event.target.value = ""; }} /></label><button className="button primary" onClick={() => { try { const next = importCollection(kind, customText); openCollection(next); void saveCollectionCloud(next); } catch { setNotice(t("请输入 2–300 件有效作品，或检查 JSON 格式。", "Enter 2–300 valid works, or check the JSON format.")); } }}>{t("载入并开始", "Load collection")}<ArrowRight size={16} /></button></div>{cloudCollections.filter((item) => item.kind === kind).length > 0 && <div className="cloud-collections"><div className="cloud-collections-heading"><span className="eyebrow">{t("我的云端清单", "MY CLOUD LISTS")}</span><button className="text-button" onClick={() => void loadCloudCollections()}>{t("刷新", "Refresh")}</button></div>{cloudCollections.filter((item) => item.kind === kind).map((item) => <div className="cloud-collection-row" key={item.id}><button className="collection-row" onClick={() => openCollection(item)}><span className="row-number">☁</span><div><strong>{item.title}</strong><small>{item.works.length} {t("件作品", "works")}</small></div><ChevronRight size={16} /></button><IconButton title={`${t("删除云端清单", "Delete cloud list")} ${item.title}`} onClick={() => void deleteCloudCollection(item)}><Trash2 size={15} /></IconButton></div>)}</div>}</section>}
    {source === "douban" && <section className="douban-source"><span className="eyebrow">{kind === "book" ? "DOUBAN / BOOKS" : kind === "music" ? "DOUBAN / MUSIC" : "DOUBAN / TOP 250"}</span><h2>{kind === "book" ? t("豆瓣读书 Top250", "Douban Book Top250") : kind === "music" ? t("豆瓣音乐 Top250", "Douban Music Top250") : t("豆瓣电影 Top250", "Douban Film Top250")}</h2><label htmlFor="douban-limit">{t("候选范围", "Candidate range")}</label><select id="douban-limit" value={doubanLimit} onChange={(event) => setDoubanLimit(Number(event.target.value))}>{[25, 50, 100, 250].map((n) => <option value={n} key={n}>Top {n}</option>)}</select><button className="button primary" disabled={busy} onClick={loadDouban}><Download size={16} />{busy ? t("正在读取…", "Loading…") : t("读取榜单", "Load collection")}</button></section>}
  </>;
}
